// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_evaluate_policy_plan
SEXP cpp_evaluate_policy_plan(List donors, LogicalMatrix pool_masks, List plan, NumericVector length_cm, NumericVector pdf_weight, double anchor_sigma);
RcppExport SEXP _tsbiomass_cpp_evaluate_policy_plan(SEXP donorsSEXP, SEXP pool_masksSEXP, SEXP planSEXP, SEXP length_cmSEXP, SEXP pdf_weightSEXP, SEXP anchor_sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type donors(donorsSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type pool_masks(pool_masksSEXP);
    Rcpp::traits::input_parameter< List >::type plan(planSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type length_cm(length_cmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pdf_weight(pdf_weightSEXP);
    Rcpp::traits::input_parameter< double >::type anchor_sigma(anchor_sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_evaluate_policy_plan(donors, pool_masks, plan, length_cm, pdf_weight, anchor_sigma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_build_benchmark_ts_errors
SEXP cpp_build_benchmark_ts_errors(List anchors, List policies, int grid_size);
RcppExport SEXP _tsbiomass_cpp_build_benchmark_ts_errors(SEXP anchorsSEXP, SEXP policiesSEXP, SEXP grid_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type anchors(anchorsSEXP);
    Rcpp::traits::input_parameter< List >::type policies(policiesSEXP);
    Rcpp::traits::input_parameter< int >::type grid_size(grid_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_build_benchmark_ts_errors(anchors, policies, grid_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_policy_equivalence_pairs
SEXP cpp_policy_equivalence_pairs(NumericMatrix policy_matrix, CharacterVector policy, CharacterVector branch, CharacterVector policy_key, double tolerance, int n_boot, int seed);
RcppExport SEXP _tsbiomass_cpp_policy_equivalence_pairs(SEXP policy_matrixSEXP, SEXP policySEXP, SEXP branchSEXP, SEXP policy_keySEXP, SEXP toleranceSEXP, SEXP n_bootSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type policy_matrix(policy_matrixSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type policy(policySEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type branch(branchSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type policy_key(policy_keySEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_policy_equivalence_pairs(policy_matrix, policy, branch, policy_key, tolerance, n_boot, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tsbiomass_cpp_evaluate_policy_plan", (DL_FUNC) &_tsbiomass_cpp_evaluate_policy_plan, 6},
    {"_tsbiomass_cpp_build_benchmark_ts_errors", (DL_FUNC) &_tsbiomass_cpp_build_benchmark_ts_errors, 3},
    {"_tsbiomass_cpp_policy_equivalence_pairs", (DL_FUNC) &_tsbiomass_cpp_policy_equivalence_pairs, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_tsbiomass(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
