# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evaluate a complete policy plan for one anchor
#'
#' @param donors Flat donor-vector payload.
#' @param pool_masks Logical matrix: unique pools by donor rows.
#' @param plan Flat compiled policy plan.
#' @param length_cm Anchor PDF length grid.
#' @param pdf_weight Anchor PDF weights.
#' @param anchor_sigma Anchor truth mean backscatter.
#'
#' @return A data frame of core policy predictions and diagnostics.
#' @noRd
cpp_evaluate_policy_plan <- function(donors, pool_masks, plan, length_cm, pdf_weight, anchor_sigma) {
    .Call(`_tsbiomass_cpp_evaluate_policy_plan`, donors, pool_masks, plan, length_cm, pdf_weight, anchor_sigma)
}

#' Build TS-error rows for a complete pseudo-anchor benchmark
#'
#' @param anchors Flat anchor vectors containing IDs, species, standardized
#'   coefficients, and study-length bounds.
#' @param policies Flat policy-performance vectors containing anchor IDs,
#'   policy metadata, standardized coefficients, and local diagnostics.
#' @param grid_size Number of equally spaced relative-length points.
#'
#' @return A data frame with one row per valid policy and relative-length point.
#' @noRd
cpp_build_benchmark_ts_errors <- function(anchors, policies, grid_size = 11L) {
    .Call(`_tsbiomass_cpp_build_benchmark_ts_errors`, anchors, policies, grid_size)
}

#' Compute every paired policy-equivalence bootstrap in one compiled call
#'
#' @param policy_matrix Species-by-policy error matrix ordered like the policy
#'   metadata vectors.
#' @param policy Policy names.
#' @param branch Equation-branch labels.
#' @param policy_key Stable policy-and-branch keys.
#' @param tolerance Practical equivalence tolerance.
#' @param n_boot Number of paired bootstrap resamples.
#' @param seed Base integer seed.
#'
#' @return Pairwise policy-equivalence data frame.
#' @noRd
cpp_policy_equivalence_pairs <- function(policy_matrix, policy, branch, policy_key, tolerance, n_boot, seed) {
    .Call(`_tsbiomass_cpp_policy_equivalence_pairs`, policy_matrix, policy, branch, policy_key, tolerance, n_boot, seed)
}

